camelCased mostly water_usage and carbon_output
matai-2019/foodlist pull request #146
Opened 2019-07-15 23:03 UTC by Rahul-Lal

Didn't touch knex table details.

2019-07-15 23:08 UTC, emilyparkes requested changes

2019-07-15 23:08 UTC, emilyparkes commented on client/components/AddFood.jsx
> +    categoryID: null,
Please change this to `categoryId` (with a lower-case `d`)

2019-07-15 23:08 UTC, emilyparkes commented on client/components/AddFood.jsx
> +            name="categoryID"
Please change this to `categoryId` (with a lower-case `d`)

2019-07-15 23:08 UTC, emilyparkes commented on server/db/category.js
> +    .join('categories', 'foods.categoryID', 'categories.id')
Please change this to `foods.category_id as categoryId` (with a lower-case `d`)

2019-07-15 23:17 UTC, emilyparkes requested changes

2019-07-15 23:17 UTC, emilyparkes commented on server/db/category.js
> +    .join('categories', 'foods.categoryId', 'categories.id')
This actually needs to be used like `foods.category_id`

2019-07-15 23:41 UTC, emilyparkes requested changes
Pull from dev to update and then approved :)

2019-07-16 02:01 UTC, bryceknz commented
Closes #128

2019-07-16 02:14 UTC, emilyparkes approved these changes

2019-07-16 02:27 UTC, merged