138 refactor actions functions names
matai-2019/foodlist pull request #148
Opened 2019-07-15 23:15 UTC by tehnools

closes #138

2019-07-15 23:28 UTC, emilyparkes requested changes
Update from dev - solve merge conflicts. Otherwise approved :)

2019-07-15 23:33 UTC, emilyparkes approved these changes

2019-07-15 23:40 UTC, emilyparkes requested changes
Changes as discussed

2019-07-16 01:24 UTC, bryceknz commented
Awesome work!! Very comprehensive 😊

2019-07-16 02:15 UTC, emilyparkes submitted a review, later dismissed

2019-07-16 02:27 UTC, emilyparkes approved these changes

2019-07-16 02:28 UTC, merged