Done the reducer thing, I think
matai-2019/foodlist pull request #64
Opened 2019-07-12 04:11 UTC by Rahul-Lal

Can you check?

2019-07-12 04:16 UTC, emilyparkes requested changes
Please mention `closes #[ticketnumberhere]` in PR description

2019-07-12 04:22 UTC, emilyparkes requested changes

2019-07-12 04:22 UTC, emilyparkes commented on client/reducers/foods.js
> +      return action.categories
This should be returning the one ✅ `category` not the list of 🚫 `categories`.

2019-07-12 04:22 UTC, emilyparkes commented on client/reducers/foods.js
> +    case GET_CATEGORIES_SUCCESS:
This should be ✅ `GET_CATEGORY_SUCCESS` not  🚫 `GET_CATEGORIES_SUCCESS`.

2019-07-12 04:36 UTC, emilyparkes commented on client/reducers/foods.js
> +export default function categoryReducer (state = {}, action) {
Please write a test for this reducer too in `tests/client/reducer/foods.test.js`

2019-07-12 11:02 UTC, bryceknz commented on client/reducers/foods.js
> +import { GET_CATEGORIES_SUCCESS } from './../actions/categories'
You should be using the action type from `/actions/category`, not `/actions/categories`.

2019-07-12 11:02 UTC, bryceknz commented on client/reducers/foods.js
> +export default function categoryReducer (state = {}, action) {
Is it not possible to have two `default` exports in one file. I suspect your intent was actually just to add to the `switch` statement the following:
```js
case GET_CATEGORY_SUCCESS:
  return action.category
```

2019-07-12 11:08 UTC, bryceknz commented on tests/client/reducers/foods.tests.js
> +  it('jest is working', () => {
@Rahul-Lal, you and I both know that this isn't what @emilyparkes meant when she said to include a test 😉

2019-07-12 11:12 UTC, bryceknz submitted a review, later dismissed
There are no changes to the `info` reducer to handle the `getCategory` action types. Confusion around `getCategory` and `getCategories` is likely due to unclear guidance given, I apologise for that.
You will need to:
- [ ] add handling for `GET_CATEGORY_PENDING` etc. into the `info` reducer
- [ ] include tests for both of these reducers (look at `/tests/client/reducers/info.js` for guidance).

2019-07-14 02:06 UTC, emilyparkes requested changes

2019-07-14 02:06 UTC, emilyparkes commented on client/reducers/foods.js
> +import { GET_CATEGORIES_SUCCESS } from './../actions/categories'
You should be using the action type from `/actions/category`, not `/actions/categories`.

2019-07-14 02:06 UTC, emilyparkes commented on client/reducers/foods.js
> +export default function categoryReducer (state = {}, action) {
Is it not possible to have two `default` exports in one file. All that is required for this ticket is to add the following to the `switch` statement:
```js
case GET_CATEGORY_SUCCESS:
  return action.category
```

2019-07-14 02:06 UTC, emilyparkes commented on tests/client/reducers/foods.tests.js
> +  it('jest is working', () => {
@Rahul-Lal, this isn't what I meant when I said to include a test 😉

2019-07-14 23:44 UTC, emilyparkes approved these changes

2019-07-14 23:48 UTC, merged